-- Seed 155+ real Indonesian skincare products
-- Brands: Skintific, Somethinc, Wardah, Glad2Glow, The Originote, NPURE, Avoskin,
--         Emina, Kahf, Y.O.U, Azarine, COSRX, Cetaphil, CeraVe, Garnier, Hada Labo,
--         Pond's, Scarlett

INSERT INTO public.products (name, brand, category, suitable_skin_types, addresses_concerns, key_ingredients, price_idr, bpom_registered, halal_certified, description, how_to_use, rating_avg)
VALUES

-- ============================================================
-- CLEANSERS (~25 products)
-- ============================================================

('5X Ceramide Low pH Cleanser', 'Skintific', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dullness','dryness','sensitivity'],
 ARRAY['ceramide','niacinamide','hyaluronic acid'],
 79000, true, false,
 'Pembersih wajah pH rendah dengan 5 ceramide untuk membersihkan tanpa bikin kulit kering atau ketarik.',
 'Basahi wajah, usapkan secukupnya, pijat lembut lalu bilas dengan air.',
 4.80),

('Low pH Clean Me Up Gel Cleanser', 'Somethinc', 'cleanser',
 ARRAY['oily','combination','normal'],
 ARRAY['acne','oiliness','large_pores'],
 ARRAY['tea tree','salicylic acid','centella asiatica'],
 69000, true, false,
 'Gel cleanser pH rendah yang efektif bersihkan minyak dan kotoran tanpa bikin kulit dehidrasi.',
 'Usapkan pada wajah basah, pijat lembut selama 30 detik, bilas bersih.',
 4.70),

('Perfect Bright Creamy Foam Brightening + Oil Control', 'Wardah', 'cleanser',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','oiliness'],
 ARRAY['niacinamide','vitamin E','licorice extract'],
 25000, true, true,
 'Creamy foam yang cerahkan wajah sekaligus kontrol minyak. Cocok buat pemakaian sehari-hari.',
 'Busa di tangan dengan air, usapkan pada wajah, pijat lembut, bilas hingga bersih.',
 4.50),

('Gentle Low pH Facial Cleanser', 'Glad2Glow', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','dryness','dullness'],
 ARRAY['centella asiatica','allantoin','panthenol'],
 45000, true, false,
 'Pembersih wajah gentle pH rendah cocok untuk semua jenis kulit, termasuk kulit sensitif.',
 'Basahi wajah, buat busa di tangan, pijat pada wajah lalu bilas bersih.',
 4.60),

('Hyaluronic Acid Low pH Facial Wash', 'The Originote', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','dullness'],
 ARRAY['hyaluronic acid','aloe vera','centella asiatica'],
 35000, true, false,
 'Facial wash dengan hyaluronic acid yang bantu jaga kelembapan kulit saat membersihkan.',
 'Busakan di tangan, usapkan pada wajah basah dengan gerakan memutar, bilas bersih.',
 4.50),

('Cica Beat The Sun Gel Cleanser', 'NPURE', 'cleanser',
 ARRAY['oily','combination','sensitive','normal'],
 ARRAY['sensitivity','redness','acne'],
 ARRAY['centella asiatica','madecassoside','salicylic acid'],
 65000, true, false,
 'Gel cleanser dengan Centella Asiatica untuk menenangkan kulit sensitif dan berjerawat.',
 'Usapkan pada wajah basah, pijat selama 1 menit, bilas dengan air bersih.',
 4.60),

('Your Skin Bae Gentle Jelly Cleanser', 'Avoskin', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dullness','sensitivity','dryness'],
 ARRAY['ceramide','hyaluronic acid','aloe vera'],
 89000, true, false,
 'Jelly cleanser yang lembut tapi efektif angkat kotoran. Tekstur unik jelly yang menyenangkan.',
 'Ambil secukupnya, usapkan pada wajah basah, pijat perlahan, bilas bersih.',
 4.70),

('Bright Stuff Face Wash', 'Emina', 'cleanser',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','oiliness'],
 ARRAY['niacinamide','vitamin C','citrus extract'],
 19000, true, true,
 'Face wash brightening affordable yang cocok buat remaja dan pemula skincare.',
 'Basahi wajah, busakan produk, pijat lembut ke wajah, bilas hingga bersih.',
 4.40),

('Gentle Exfoliating Face Wash', 'Kahf', 'cleanser',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','dullness','large_pores'],
 ARRAY['salicylic acid','bamboo charcoal','menthol'],
 35000, true, true,
 'Face wash pria dengan gentle exfoliation dari bamboo charcoal. Bersihkan pori tanpa bikin kering.',
 'Basahi wajah, usapkan dan pijat selama 30 detik, bilas bersih. Gunakan pagi dan malam.',
 4.50),

('Amino Low pH Gentle Cleanser', 'Y.O.U', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','dryness','dullness'],
 ARRAY['amino acid','centella asiatica','allantoin'],
 55000, true, false,
 'Amino acid-based cleanser pH rendah yang super gentle untuk kulit sensitif dan reaktif.',
 'Busakan di tangan, pijat lembut pada wajah basah, bilas bersih.',
 4.60),

('Hydrasoothe SOS Gel Cleanser', 'Azarine', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','dryness','redness'],
 ARRAY['hyaluronic acid','aloe vera','centella asiatica'],
 39000, true, false,
 'Gel cleanser yang lembut dan menenangkan, cocok untuk kulit dehidrasi dan sensitif.',
 'Usapkan pada wajah basah, pijat lembut, bilas dengan air hingga bersih.',
 4.50),

('Low pH Good Morning Gel Cleanser', 'COSRX', 'cleanser',
 ARRAY['oily','combination','normal'],
 ARRAY['acne','oiliness','large_pores'],
 ARRAY['tea tree oil','BHA','betaine salicylate'],
 99000, true, false,
 'Gel cleanser pH rendah best-seller dari Korea. Tea tree oil bantu kontrol jerawat ringan.',
 'Busakan di tangan, pijat pada wajah basah selama 30 detik, bilas bersih. Ideal untuk pagi hari.',
 4.80),

('Gentle Skin Cleanser', 'Cetaphil', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','dryness'],
 ARRAY['glycerin','panthenol','niacinamide'],
 125000, true, false,
 'Cleanser paling gentle, direkomendasikan dermatolog untuk semua jenis kulit termasuk super sensitif.',
 'Bisa dipakai dengan atau tanpa air. Usapkan pada wajah, pijat lembut, bilas atau usap bersih.',
 4.80),

('Hydrating Facial Cleanser', 'CeraVe', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity'],
 ARRAY['ceramide','hyaluronic acid','glycerin'],
 179000, true, false,
 'Cleanser dengan 3 essential ceramide untuk bersihkan sekaligus jaga skin barrier.',
 'Basahi wajah, pijat produk secukupnya, bilas bersih. Gunakan pagi dan malam.',
 4.80),

('Bright Complete Speed Serum Foam', 'Garnier', 'cleanser',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['vitamin C','lemon extract','salicylic acid'],
 35000, true, false,
 'Foam cleanser dengan vitamin C untuk cerahkan kulit dan samarkan noda hitam.',
 'Basahi wajah, busakan produk, pijat selama 30 detik, bilas hingga bersih.',
 4.50),

('Gokujyun Face Wash', 'Hada Labo', 'cleanser',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dryness','dullness'],
 ARRAY['hyaluronic acid','sodium hyaluronate'],
 55000, true, false,
 'Facial wash dengan hyaluronic acid yang bikin kulit tetap lembap setelah cuci muka.',
 'Busakan di tangan atau net, pijat pada wajah basah, bilas bersih.',
 4.70),

('Bright Beauty Facial Foam', 'Pond''s', 'cleanser',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots','oiliness'],
 ARRAY['niacinamide','vitamin B3','glycerin'],
 22000, true, false,
 'Facial foam brightening yang terjangkau untuk pemakaian harian. Cerahkan wajah kusam.',
 'Basahi wajah, busakan secukupnya, pijat lembut, bilas bersih. Gunakan 2x sehari.',
 4.40),

('Brightly Ever After Brightening Facial Wash', 'Scarlett', 'cleanser',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots','oiliness'],
 ARRAY['glutathione','niacinamide','vitamin E'],
 35000, true, false,
 'Facial wash dengan glutathione untuk mencerahkan dan menyamarkan noda hitam.',
 'Busakan di tangan, usapkan pada wajah basah, pijat lembut, bilas hingga bersih.',
 4.40),

('5X Ceramide No-Rinse Micellar Water', 'Skintific', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','dryness'],
 ARRAY['ceramide','niacinamide','panthenol'],
 89000, true, false,
 'Micellar water dengan 5 ceramide untuk bersihkan makeup dan kotoran tanpa bikin iritasi.',
 'Tuang pada kapas, usap lembut pada wajah sampai bersih. Tidak perlu dibilas.',
 4.70),

('Alpha Arbutin + Niacinamide Brightening Face Wash', 'Glad2Glow', 'cleanser',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots','oiliness'],
 ARRAY['alpha arbutin','niacinamide','glycerin'],
 42000, true, false,
 'Face wash brightening dengan alpha arbutin dan niacinamide untuk kulit cerah merata.',
 'Basahi wajah, busakan produk, pijat selama 30-60 detik, bilas bersih.',
 4.50),

('Oil Control Face Wash', 'Kahf', 'cleanser',
 ARRAY['oily','combination'],
 ARRAY['oiliness','acne','large_pores'],
 ARRAY['salicylic acid','tea tree','zinc'],
 35000, true, true,
 'Face wash pria yang efektif kontrol minyak berlebih dan cegah jerawat.',
 'Basahi wajah, usapkan produk dan pijat selama 30 detik, bilas bersih.',
 4.50),

('Brightening Micellar Water', 'Wardah', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dullness','sensitivity'],
 ARRAY['niacinamide','rose water','allantoin'],
 35000, true, true,
 'Micellar water lembut untuk angkat makeup dan kotoran tanpa perlu dibilas.',
 'Tuang pada kapas, usap lembut pada wajah. Ulangi sampai kapas bersih.',
 4.50),

('AC Collection Calming Foam Cleanser', 'COSRX', 'cleanser',
 ARRAY['oily','combination','sensitive'],
 ARRAY['acne','redness','sensitivity'],
 ARRAY['BHA','tea tree','madecassoside'],
 129000, true, false,
 'Foam cleanser khusus kulit berjerawat. Tenangkan dan bersihkan tanpa over-drying.',
 'Busakan di tangan, usapkan pada wajah basah, pijat 30 detik, bilas bersih.',
 4.70),

('Daily Moisturizing Facial Wash', 'Cetaphil', 'cleanser',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity'],
 ARRAY['aloe vera','glycerin','vitamin B5'],
 95000, true, false,
 'Facial wash harian yang super lembut, cocok untuk kulit kering dan sensitif.',
 'Basahi wajah, usapkan secukupnya, pijat lembut, bilas bersih.',
 4.70),

-- ============================================================
-- TONERS (~20 products)
-- ============================================================

('5X Ceramide Barrier Repair Toner', 'Skintific', 'toner',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity','dullness'],
 ARRAY['ceramide','hyaluronic acid','niacinamide'],
 99000, true, false,
 'Toner dengan 5 ceramide untuk repair skin barrier. Cocok untuk kulit sensitif dan dehidrasi.',
 'Tuang pada kapas atau telapak tangan, tepuk-tepuk lembut pada wajah setelah cuci muka.',
 4.80),

('AHA BHA PHA 30 Days Miracle Toner', 'Somethinc', 'toner',
 ARRAY['oily','combination','normal'],
 ARRAY['acne','large_pores','dullness','blackheads'],
 ARRAY['AHA','BHA','PHA','niacinamide'],
 89000, true, false,
 'Exfoliating toner dengan AHA BHA PHA untuk angkat sel kulit mati dan kecilkan pori.',
 'Gunakan 2-3x seminggu. Tuang pada kapas, usap lembut pada wajah. Hindari area mata.',
 4.60),

('Lightening Face Toner', 'Wardah', 'toner',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots','oiliness'],
 ARRAY['niacinamide','licorice extract','allantoin'],
 28000, true, true,
 'Toner pencerah harian yang terjangkau dengan niacinamide untuk kulit cerah merata.',
 'Tuang pada kapas, usap lembut pada wajah setelah cuci muka. Gunakan pagi dan malam.',
 4.40),

('2% Salicylic Acid Toner', 'Glad2Glow', 'toner',
 ARRAY['oily','combination'],
 ARRAY['acne','oiliness','blackheads','large_pores'],
 ARRAY['salicylic acid','tea tree','witch hazel'],
 55000, true, false,
 'Exfoliating toner dengan 2% salicylic acid untuk kulit berminyak dan berjerawat.',
 'Gunakan malam hari saja. Tuang pada kapas, usap lembut pada wajah. Pakai sunscreen besoknya.',
 4.50),

('Centella Water Alcohol Free Toner', 'NPURE', 'toner',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','redness','acne_scars'],
 ARRAY['centella asiatica','madecassoside','green tea'],
 79000, true, false,
 'Toner tanpa alkohol dengan Centella Asiatica untuk menenangkan kulit sensitif dan merah-merah.',
 'Tuang pada telapak tangan atau kapas, tepuk-tepuk lembut pada wajah bersih.',
 4.70),

('Your Skin Bae Toner', 'Avoskin', 'toner',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots','large_pores'],
 ARRAY['niacinamide','AHA','BHA','PHA'],
 99000, true, false,
 'Exfoliating toner multi-acid yang bantu cerahkan dan haluskan tekstur kulit.',
 'Gunakan malam hari, 2-3x seminggu. Tuang pada kapas, usap searah pada wajah.',
 4.60),

('Tone Up Toner', 'Emina', 'toner',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','oiliness'],
 ARRAY['niacinamide','chamomile','allantoin'],
 25000, true, true,
 'Toner ringan dan affordable untuk pemula skincare. Segar dan ringan di kulit.',
 'Tuang pada kapas, usap lembut pada wajah bersih setelah cuci muka.',
 4.30),

('Hydrating Toner', 'Kahf', 'toner',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dryness','dullness'],
 ARRAY['hyaluronic acid','aloe vera','allantoin'],
 45000, true, true,
 'Toner pria yang ringan dan hydrating. Siapkan kulit untuk moisturizer.',
 'Tuang pada telapak tangan, tepuk-tepuk pada wajah bersih. Gunakan setelah cuci muka.',
 4.50),

('AHA BHA PHA 30 Days Miracle Toner', 'COSRX', 'toner',
 ARRAY['oily','combination','normal'],
 ARRAY['acne','blackheads','large_pores','dullness'],
 ARRAY['AHA','BHA','PHA','tea tree'],
 175000, true, false,
 'Best-seller toner dari COSRX untuk kulit berjerawat. Triple acid untuk eksfoliasi lembut.',
 'Tuang pada kapas, usap pada wajah bersih. Gunakan malam hari, bisa setiap hari untuk kulit terbiasa.',
 4.80),

('Gokujyun Hydrating Lotion', 'Hada Labo', 'toner',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','dullness'],
 ARRAY['hyaluronic acid','sodium hyaluronate','glycerin'],
 75000, true, false,
 'Hydrating toner legendaris dengan multiple hyaluronic acid. Super melembapkan.',
 'Tuang pada telapak tangan, tepuk-tepuk lembut pada wajah. Layer 2-3x untuk extra hydration.',
 4.80),

('Bright Beauty Brightening Toner', 'Pond''s', 'toner',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['niacinamide','glycerin','vitamin B3'],
 35000, true, false,
 'Toner pencerah dengan niacinamide untuk kulit kusam dan tidak merata.',
 'Tuang pada kapas, usap lembut pada wajah bersih. Gunakan pagi dan malam.',
 4.40),

('Sakura White Pinkish Radiance Skin Lotion', 'Garnier', 'toner',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['sakura extract','hyaluronic acid'],
 45000, true, false,
 'Toner ringan dengan sakura extract untuk wajah cerah bercahaya pink.',
 'Tuang pada kapas, usap lembut ke seluruh wajah setelah cuci muka.',
 4.40),

('Niacinamide 5% + Moisture Sabi Beet Toner', 'The Originote', 'toner',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','oiliness','large_pores'],
 ARRAY['niacinamide','beet extract','hyaluronic acid'],
 45000, true, false,
 'Toner dengan 5% niacinamide untuk kontrol minyak dan cerahkan kulit kusam.',
 'Tuang pada kapas atau telapak tangan, tepuk-tepuk pada wajah setelah cuci muka.',
 4.50),

('Witch Hazel Pore Control Toner', 'Y.O.U', 'toner',
 ARRAY['oily','combination'],
 ARRAY['oiliness','large_pores','acne'],
 ARRAY['witch hazel','salicylic acid','tea tree'],
 49000, true, false,
 'Toner pore control dengan witch hazel untuk minimalisir tampilan pori-pori besar.',
 'Tuang pada kapas, usap pada area T-zone dan pipi. Gunakan setelah cuci muka.',
 4.50),

('Hydrasoothe Pore Smooth Refining Toner', 'Azarine', 'toner',
 ARRAY['oily','combination','normal'],
 ARRAY['large_pores','oiliness','dullness'],
 ARRAY['BHA','niacinamide','centella asiatica'],
 45000, true, false,
 'Toner untuk haluskan pori dan kontrol minyak. Bikin kulit smooth dan halus.',
 'Tuang pada kapas, usap searah pada wajah bersih. Fokus di area pori besar.',
 4.50),

('Brightly Ever After Brightening Body Toner', 'Scarlett', 'toner',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['glutathione','niacinamide','allantoin'],
 55000, true, false,
 'Toner badan untuk cerahkan dan ratakan warna kulit tubuh.',
 'Tuang pada kapas atau tangan, usapkan pada area badan yang ingin dicerahkan.',
 4.30),

('UV Bright Skincare Toner', 'Wardah', 'toner',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots','oiliness'],
 ARRAY['niacinamide','vitamin C','hyaluronic acid'],
 38000, true, true,
 'Toner dengan vitamin C dan niacinamide untuk cerahkan kulit yang sering terpapar matahari.',
 'Tuang pada kapas, usap pada wajah bersih setelah cuci muka. Gunakan pagi dan malam.',
 4.40),

('Full Power Moisture Toner', 'COSRX', 'toner',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','dullness'],
 ARRAY['propolis','hyaluronic acid','panthenol'],
 159000, true, false,
 'Hydrating toner dengan propolis extract untuk kulit dehidrasi dan sensitif.',
 'Tuang pada telapak tangan, tepuk-tepuk pada wajah. Bisa di-layer beberapa kali.',
 4.70),

('Gokujyun Premium Hydrating Lotion', 'Hada Labo', 'toner',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','dullness','fine_lines'],
 ARRAY['hyaluronic acid','urea','squalane'],
 115000, true, false,
 'Versi premium dengan 5 jenis hyaluronic acid. Ultra melembapkan untuk kulit sangat kering.',
 'Tuang pada tangan, tepuk lembut pada wajah. Cukup 2-3 tetes per pemakaian.',
 4.80),

-- ============================================================
-- SERUMS (~30 products)
-- ============================================================

('5X Ceramide Barrier Repair Serum', 'Skintific', 'serum',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','dryness','redness'],
 ARRAY['ceramide','cholesterol','fatty acids','niacinamide'],
 129000, true, false,
 'Serum repair barrier dengan 5 ceramide. Best-seller untuk pulihkan skin barrier rusak.',
 'Teteskan 2-3 tetes pada wajah bersih, tepuk-tepuk lembut sampai meresap. Gunakan pagi dan malam.',
 4.80),

('10% Niacinamide + Moisture Beet Serum', 'Skintific', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','large_pores','dullness','dark_spots'],
 ARRAY['niacinamide','beet extract','hyaluronic acid'],
 119000, true, false,
 'Serum 10% niacinamide untuk kontrol minyak, kecilkan pori, dan cerahkan noda hitam.',
 'Teteskan 3-4 tetes pada wajah, tepuk lembut sampai meresap. Gunakan pagi dan/atau malam.',
 4.70),

('Niacinamide + Zinc Pore Minimizer Serum', 'Somethinc', 'serum',
 ARRAY['oily','combination'],
 ARRAY['oiliness','large_pores','acne'],
 ARRAY['niacinamide','zinc PCA','hyaluronic acid'],
 89000, true, false,
 'Serum niacinamide + zinc untuk kontrol minyak berlebih dan minimalisir tampilan pori.',
 'Teteskan 2-3 tetes pada wajah bersih, tepuk lembut. Bisa dicampur moisturizer.',
 4.70),

('10% Vitamin C + Niacinamide Brightening Serum', 'Somethinc', 'serum',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','dark_spots','acne_scars'],
 ARRAY['vitamin C','niacinamide','ferulic acid'],
 99000, true, false,
 'Serum vitamin C stabil untuk cerahkan dan ratakan warna kulit. Anti-oksidan kuat.',
 'Gunakan pagi hari. Teteskan 2-3 tetes, tepuk lembut. Wajib pakai sunscreen setelahnya.',
 4.60),

('1% Retinol Night Serum', 'Somethinc', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['acne','fine_lines','dullness','large_pores'],
 ARRAY['retinol','bakuchiol','squalane'],
 109000, true, false,
 'Retinol serum untuk anti-aging dan perbaiki tekstur kulit. Mulai dari 1-2x seminggu.',
 'Gunakan MALAM hari saja. Teteskan 2-3 tetes setelah toner. Mulai pelan-pelan, tingkatkan frekuensi.',
 4.60),

('C-Defense Brightening Serum', 'Wardah', 'serum',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['vitamin C','niacinamide','vitamin E'],
 69000, true, true,
 'Serum vitamin C dengan harga terjangkau dari Wardah. Cerahkan kulit kusam.',
 'Teteskan 3-4 tetes pada wajah bersih, tepuk lembut. Gunakan pagi hari dengan sunscreen.',
 4.50),

('Skin Perfect Serum AHA BHA PHA', 'Wardah', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['acne','dullness','large_pores','blackheads'],
 ARRAY['AHA','BHA','PHA','centella asiatica'],
 79000, true, true,
 'Triple acid serum untuk eksfoliasi dan haluskan tekstur kulit berjerawat.',
 'Gunakan malam hari, 2-3x seminggu. Teteskan 2-3 tetes, hindari area mata.',
 4.50),

('2% Salicylic Acid Anti-Acne Serum', 'Glad2Glow', 'serum',
 ARRAY['oily','combination'],
 ARRAY['acne','blackheads','oiliness'],
 ARRAY['salicylic acid','niacinamide','tea tree'],
 55000, true, false,
 'Serum anti-jerawat dengan 2% salicylic acid. Bersihkan pori dari dalam.',
 'Teteskan pada area berjerawat. Gunakan malam hari, 2-3x seminggu di awal pemakaian.',
 4.50),

('5% Niacinamide Serum', 'Glad2Glow', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','large_pores','dullness','dark_spots'],
 ARRAY['niacinamide','zinc PCA','hyaluronic acid'],
 49000, true, false,
 'Serum niacinamide affordable untuk kontrol minyak dan cerahkan kulit.',
 'Teteskan 3-4 tetes pada wajah, tepuk lembut. Gunakan pagi dan/atau malam.',
 4.50),

('Hyaluronic Acid Hydrating Serum', 'The Originote', 'serum',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','dullness','fine_lines'],
 ARRAY['hyaluronic acid','sodium hyaluronate','panthenol'],
 39000, true, false,
 'Serum hyaluronic acid untuk hidrasi intens. Plumping effect bikin kulit kenyal.',
 'Teteskan 3-4 tetes pada wajah lembap, tepuk lembut. Layer dengan moisturizer.',
 4.50),

('Retinol Serum', 'The Originote', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['acne','fine_lines','dullness'],
 ARRAY['retinol','niacinamide','squalane'],
 45000, true, false,
 'Retinol serum pemula yang affordable. Bantu perbaiki tekstur dan fine lines.',
 'Gunakan malam hari. Teteskan 2-3 tetes, mulai 1-2x seminggu. Wajib sunscreen besoknya.',
 4.40),

('Cica Beat The Sun Serum', 'NPURE', 'serum',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','redness','acne_scars'],
 ARRAY['centella asiatica','madecassoside','asiaticoside'],
 89000, true, false,
 'Serum Centella terbaik lokal. Tenangkan kulit sensitif dan bantu fading bekas jerawat.',
 'Teteskan 3-4 tetes pada wajah bersih, tepuk lembut. Aman digunakan pagi dan malam.',
 4.70),

('Marigold Brightening Serum', 'NPURE', 'serum',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','dark_spots','acne_scars'],
 ARRAY['vitamin C','marigold extract','niacinamide'],
 89000, true, false,
 'Serum pencerah dengan marigold extract dan vitamin C untuk kulit glowing.',
 'Teteskan 3-4 tetes pagi hari, tepuk lembut. Pakai sunscreen setelahnya.',
 4.60),

('Your Skin Bae Retinol Serum', 'Avoskin', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['acne','fine_lines','large_pores','dullness'],
 ARRAY['retinol','niacinamide','bakuchiol'],
 149000, true, false,
 'Retinol serum premium lokal dengan bakuchiol untuk anti-aging tanpa iritasi berlebih.',
 'Gunakan malam hari. Mulai 1-2x seminggu, naikkan bertahap. Wajib sunscreen pagi harinya.',
 4.60),

('Your Skin Bae Niacinamide 7% Serum', 'Avoskin', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','large_pores','dullness','dark_spots'],
 ARRAY['niacinamide','alpha arbutin','hyaluronic acid'],
 129000, true, false,
 'Serum 7% niacinamide premium untuk kontrol minyak, cerahkan, dan samarkan pori.',
 'Teteskan 3-4 tetes pada wajah bersih, tepuk lembut sampai meresap.',
 4.60),

('Bright Stuff Serum', 'Emina', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['niacinamide','vitamin C','licorice extract'],
 35000, true, true,
 'Serum pencerah affordable untuk remaja. Ringan dan cepat meresap.',
 'Teteskan 3-4 tetes pada wajah, tepuk lembut. Gunakan pagi dan/atau malam.',
 4.30),

('All Day Skin Barrier Serum', 'Kahf', 'serum',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dryness','sensitivity','dullness'],
 ARRAY['ceramide','hyaluronic acid','centella asiatica'],
 55000, true, true,
 'Serum pria dengan ceramide untuk jaga skin barrier tetap sehat.',
 'Teteskan 2-3 tetes pada wajah bersih, tepuk lembut. Gunakan setelah toner.',
 4.50),

('Triple C Brightening Serum', 'Y.O.U', 'serum',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','dark_spots','acne_scars'],
 ARRAY['vitamin C','niacinamide','alpha arbutin'],
 65000, true, false,
 'Triple brightening serum dengan 3 bahan aktif pencerah sekaligus.',
 'Teteskan 3-4 tetes pagi hari pada wajah bersih. Wajib pakai sunscreen.',
 4.50),

('Hydrasoothe Cica Serum', 'Azarine', 'serum',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','redness','acne_scars'],
 ARRAY['centella asiatica','allantoin','panthenol'],
 49000, true, false,
 'Serum cica untuk menenangkan kulit sensitif dan bantu recovery dari jerawat.',
 'Teteskan 3-4 tetes pada wajah bersih, tepuk lembut. Aman untuk pagi dan malam.',
 4.50),

('Snail Mucin 96% Power Repairing Essence', 'COSRX', 'serum',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','dullness','acne_scars','fine_lines'],
 ARRAY['snail secretion filtrate','betaine','hyaluronic acid'],
 189000, true, false,
 'Essence snail mucin legendaris untuk repair, hidrasi, dan fade acne scars.',
 'Tuang secukupnya pada telapak tangan, tepuk-tepuk pada wajah. Bisa dipakai pagi dan malam.',
 4.90),

('Advanced Snail 96 Mucin Power Essence', 'COSRX', 'serum',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','dullness','fine_lines'],
 ARRAY['snail secretion filtrate','sodium hyaluronate','allantoin'],
 245000, true, false,
 'Versi jumbo essence snail mucin. Multifungsi untuk hidrasi, repair, dan anti-aging.',
 'Tuang secukupnya, tepuk pada wajah bersih. Gunakan setelah toner.',
 4.90),

('Gokujyun Premium Hyaluronic Acid Serum', 'Hada Labo', 'serum',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','dullness','fine_lines'],
 ARRAY['hyaluronic acid','urea','squalane','ceramide'],
 155000, true, false,
 'Serum premium dengan 5 jenis hyaluronic acid untuk hidrasi super intens.',
 'Teteskan 2-3 tetes pada wajah lembap, tepuk lembut. Layer dengan moisturizer.',
 4.80),

('Bright Complete Vitamin C Booster Serum', 'Garnier', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['vitamin C','niacinamide','salicylic acid'],
 85000, true, false,
 'Serum vitamin C dari Garnier untuk mencerahkan dan samarkan dark spots.',
 'Teteskan 3-4 tetes pada wajah, tepuk lembut. Gunakan pagi hari dengan sunscreen.',
 4.50),

('Bright Beauty Serum', 'Pond''s', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['niacinamide','gluta-boost','vitamin E'],
 45000, true, false,
 'Serum pencerah terjangkau dengan niacinamide untuk kulit cerah dan glowing.',
 'Teteskan 2-3 tetes, tepuk lembut pada wajah. Gunakan pagi dan malam.',
 4.40),

('Brightly Ever After Brightening Serum', 'Scarlett', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots','acne_scars'],
 ARRAY['glutathione','niacinamide','phyto whitening'],
 75000, true, false,
 'Serum brightening dengan glutathione untuk mencerahkan dan meratakan warna kulit.',
 'Teteskan 3-4 tetes pada wajah bersih, tepuk lembut. Gunakan sebelum moisturizer.',
 4.40),

('Acne Spot Serum', 'Scarlett', 'serum',
 ARRAY['oily','combination'],
 ARRAY['acne','acne_scars','oiliness'],
 ARRAY['salicylic acid','tea tree','centella asiatica'],
 75000, true, false,
 'Serum khusus untuk spot treatment jerawat dan bekas jerawat.',
 'Teteskan langsung pada area berjerawat. Gunakan malam hari.',
 4.30),

('BHA Blackhead Power Liquid', 'COSRX', 'serum',
 ARRAY['oily','combination'],
 ARRAY['blackheads','large_pores','acne','oiliness'],
 ARRAY['BHA','betaine salicylate','willow bark'],
 165000, true, false,
 'BHA liquid untuk atasi komedo hitam dan bersihkan pori dari dalam.',
 'Setelah toner, tuang pada kapas, usap pada area berkomedo. Mulai 2-3x seminggu.',
 4.70),

('AHA/BHA Clarifying Treatment Toner', 'COSRX', 'serum',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','large_pores','blackheads'],
 ARRAY['AHA','BHA','apple water'],
 155000, true, false,
 'Treatment toner dengan AHA/BHA untuk eksfoliasi harian yang gentle.',
 'Tuang pada kapas, usap pada wajah setelah cleanser. Bisa digunakan setiap hari.',
 4.70),

('Alpha Arbutin Brightening Serum', 'Glad2Glow', 'serum',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','dark_spots','acne_scars'],
 ARRAY['alpha arbutin','niacinamide','hyaluronic acid'],
 55000, true, false,
 'Serum alpha arbutin untuk mencerahkan dan samarkan noda hitam serta bekas jerawat.',
 'Teteskan 3-4 tetes pada wajah bersih, tepuk lembut. Gunakan pagi dan/atau malam.',
 4.50),

-- ============================================================
-- MOISTURIZERS (~25 products)
-- ============================================================

('5X Ceramide Barrier Moisture Gel', 'Skintific', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity'],
 ARRAY['ceramide','hyaluronic acid','centella asiatica'],
 109000, true, false,
 'Moisturizer gel best-seller dengan 5 ceramide. Ringan tapi super melembapkan.',
 'Ambil secukupnya, usapkan pada wajah setelah serum. Bisa juga dijadikan sleeping mask.',
 4.90),

('Ceramic Skin Saviour Moisturizer', 'Somethinc', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity','redness'],
 ARRAY['ceramide','squalane','centella asiatica'],
 109000, true, false,
 'Moisturizer repair barrier dengan ceramide dan squalane untuk kulit sensitif.',
 'Ambil secukupnya, usapkan merata pada wajah setelah serum. Gunakan pagi dan malam.',
 4.70),

('Hydra Rose Gel Moisturizer', 'Wardah', 'moisturizer',
 ARRAY['oily','combination','normal'],
 ARRAY['dryness','dullness'],
 ARRAY['hyaluronic acid','rose water','niacinamide'],
 55000, true, true,
 'Gel moisturizer ringan dengan rose water. Fresh dan tidak lengket untuk kulit berminyak.',
 'Ambil secukupnya, usapkan merata pada wajah. Gunakan sebagai step terakhir skincare.',
 4.50),

('UV Shield Aqua Fresh Gel SPF 50', 'Wardah', 'moisturizer',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','dullness'],
 ARRAY['niacinamide','hyaluronic acid','aloe vera'],
 49000, true, true,
 'Gel moisturizer ringan dari Wardah yang cocok untuk cuaca panas Indonesia.',
 'Usapkan merata pada wajah setelah serum, gunakan pagi dan malam.',
 4.50),

('Watermelon + Niacinamide Moisturizer', 'Glad2Glow', 'moisturizer',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','dullness','large_pores'],
 ARRAY['niacinamide','watermelon extract','hyaluronic acid'],
 55000, true, false,
 'Water gel moisturizer super ringan dengan watermelon. Anti-lengket dan segar.',
 'Ambil secukupnya, usapkan pada wajah bersih setelah serum.',
 4.50),

('Centella Moisturizer', 'The Originote', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','redness','dryness'],
 ARRAY['centella asiatica','allantoin','hyaluronic acid'],
 42000, true, false,
 'Moisturizer centella yang affordable untuk menenangkan kulit sensitif.',
 'Usapkan secukupnya pada wajah sebagai step terakhir skincare.',
 4.40),

('Cica Beat The Sun Moisturizer', 'NPURE', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','redness','dryness'],
 ARRAY['centella asiatica','madecassoside','squalane'],
 79000, true, false,
 'Moisturizer cica yang ringan tapi intensely moisturizing. Untuk kulit sensitif.',
 'Ambil secukupnya, usapkan merata pada wajah setelah serum.',
 4.70),

('Your Skin Bae Marine Collagen Moisturizer', 'Avoskin', 'moisturizer',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dryness','fine_lines','dullness'],
 ARRAY['marine collagen','hyaluronic acid','squalane'],
 129000, true, false,
 'Moisturizer dengan marine collagen untuk anti-aging dan hidrasi intens.',
 'Usapkan secukupnya pada wajah pagi dan malam sebagai step terakhir.',
 4.60),

('Beauty Bliss Moisturizing Cream', 'Emina', 'moisturizer',
 ARRAY['oily','combination','normal'],
 ARRAY['dryness','dullness'],
 ARRAY['aloe vera','vitamin E','allantoin'],
 25000, true, true,
 'Moisturizer ringan dan affordable buat remaja. Tidak lengket dan cepat meresap.',
 'Ambil secukupnya, usapkan pada wajah sebagai step terakhir.',
 4.30),

('Skin Energizing & Brightening Moisturizer', 'Kahf', 'moisturizer',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dryness'],
 ARRAY['niacinamide','hyaluronic acid','vitamin E'],
 55000, true, true,
 'Moisturizer pria ringan yang cerahkan dan energize kulit kusam.',
 'Ambil secukupnya, usapkan merata pada wajah setelah serum pagi dan malam.',
 4.50),

('Golden Age Cream', 'Y.O.U', 'moisturizer',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['fine_lines','dryness','dullness'],
 ARRAY['retinol','collagen','hyaluronic acid'],
 85000, true, false,
 'Anti-aging cream dengan retinol dan collagen untuk kulit lebih kencang.',
 'Gunakan malam hari. Ambil secukupnya, usapkan merata pada wajah.',
 4.50),

('Hydrasoothe SOS Cica Gel Moisturizer', 'Azarine', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','redness','dryness'],
 ARRAY['centella asiatica','aloe vera','allantoin'],
 49000, true, false,
 'Gel moisturizer cica super lembut untuk kulit sensitif dan iritasi.',
 'Ambil secukupnya, usapkan pada wajah. Bisa juga jadi sleeping mask.',
 4.50),

('Oil Free Moisturizing Lotion', 'COSRX', 'moisturizer',
 ARRAY['oily','combination'],
 ARRAY['oiliness','dryness'],
 ARRAY['birch sap','hyaluronic acid','panthenol'],
 155000, true, false,
 'Moisturizer oil-free dari COSRX. Ringan dan cocok untuk kulit berminyak.',
 'Ambil secukupnya, usapkan merata pada wajah setelah serum.',
 4.70),

('Advanced Snail 92 All In One Cream', 'COSRX', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','acne_scars','fine_lines','dullness'],
 ARRAY['snail secretion filtrate','betaine','hyaluronic acid'],
 199000, true, false,
 'Cream snail mucin multifungsi untuk repair, hidrasi, dan anti-aging.',
 'Ambil secukupnya, usapkan merata pada wajah sebagai step terakhir.',
 4.80),

('Moisturizing Cream', 'Cetaphil', 'moisturizer',
 ARRAY['dry','sensitive','normal'],
 ARRAY['dryness','sensitivity'],
 ARRAY['glycerin','sweet almond oil','niacinamide'],
 155000, true, false,
 'Rich cream untuk kulit kering dan sangat kering. Direkomendasikan dermatolog.',
 'Ambil secukupnya, usapkan merata pada wajah dan badan yang kering.',
 4.80),

('Moisturizing Lotion', 'CeraVe', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity'],
 ARRAY['ceramide','hyaluronic acid','glycerin'],
 195000, true, false,
 'Lotion dengan 3 essential ceramide dan MVE technology untuk hidrasi 24 jam.',
 'Usapkan secukupnya pada wajah dan badan setelah mandi atau setelah serum.',
 4.80),

('Skin Naturals Bright Complete Night Cream', 'Garnier', 'moisturizer',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['vitamin C','lemon extract','yoghurt'],
 65000, true, false,
 'Night cream pencerah yang bekerja semalaman untuk kulit cerah di pagi hari.',
 'Gunakan malam hari. Ambil secukupnya, usapkan merata pada wajah.',
 4.40),

('Gokujyun Hydrating Cream', 'Hada Labo', 'moisturizer',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dryness','dullness'],
 ARRAY['hyaluronic acid','squalane','ceramide'],
 99000, true, false,
 'Hydrating cream dengan hyaluronic acid untuk lock-in kelembapan sepanjang hari.',
 'Ambil secukupnya, usapkan merata pada wajah setelah lotion/toner.',
 4.70),

('Bright Beauty Super Cream', 'Pond''s', 'moisturizer',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['niacinamide','vitamin E','hyaluronic acid'],
 55000, true, false,
 'Cream pencerah yang ringan untuk penggunaan harian.',
 'Ambil secukupnya, usapkan merata pada wajah pagi dan/atau malam.',
 4.40),

('Brightly Ever After Day Cream', 'Scarlett', 'moisturizer',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['glutathione','niacinamide','hyaluronic acid'],
 55000, true, false,
 'Day cream brightening dengan glutathione untuk kulit cerah seharian.',
 'Gunakan pagi hari, usapkan merata setelah serum dan sebelum sunscreen.',
 4.30),

('5X Ceramide Skin Barrier Repair Cream', 'Skintific', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','dryness','redness'],
 ARRAY['ceramide','squalane','cholesterol','shea butter'],
 139000, true, false,
 'Cream versi lebih rich dari gel moisturizer. Untuk kulit kering dan very damaged barrier.',
 'Ambil secukupnya, usapkan pada wajah malam hari. Bisa di-layer dengan gel di pagi hari.',
 4.80),

('Mugwort Cica Moisturizer', 'NPURE', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','redness','acne_scars'],
 ARRAY['centella asiatica','mugwort','madecassoside'],
 79000, true, false,
 'Moisturizer cica + mugwort untuk calming intensif dan repair kulit merah-merah.',
 'Usapkan secukupnya pada wajah sebagai step terakhir skincare pagi dan malam.',
 4.60),

('Rice Gel Moisturizer', 'Somethinc', 'moisturizer',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','oiliness'],
 ARRAY['rice extract','niacinamide','hyaluronic acid'],
 95000, true, false,
 'Gel moisturizer ringan dengan rice extract untuk kulit cerah dan glowing.',
 'Ambil secukupnya, usapkan merata pada wajah setelah serum.',
 4.60),

('Amino Acid Moisturizer', 'Y.O.U', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity'],
 ARRAY['amino acid','hyaluronic acid','ceramide'],
 65000, true, false,
 'Moisturizer gentle dengan amino acid untuk kulit sensitif dan dehidrasi.',
 'Usapkan secukupnya pada wajah sebagai step terakhir pagi dan malam.',
 4.50),

('Daily Moisturizing Lotion', 'Cetaphil', 'moisturizer',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity'],
 ARRAY['glycerin','panthenol','niacinamide'],
 135000, true, false,
 'Lotion ringan harian yang cocok untuk kulit sensitif. Non-comedogenic.',
 'Usapkan secukupnya pada wajah dan badan. Gunakan setelah mandi.',
 4.70),

-- ============================================================
-- SUNSCREENS (~25 products)
-- ============================================================

('5X Ceramide Serum Sunscreen SPF 50 PA++++', 'Skintific', 'sunscreen',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dullness','sensitivity'],
 ARRAY['ceramide','niacinamide','hyaluronic acid'],
 89000, true, false,
 'Sunscreen serum-like yang ringan dengan 5 ceramide. No white cast, cocok semua skin tone.',
 'Usapkan 2 jari pada wajah sebagai step terakhir skincare pagi. Reapply tiap 2-3 jam.',
 4.80),

('Holyshield! Sunscreen Comfort Corrector Serum SPF 50+', 'Somethinc', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','dullness'],
 ARRAY['niacinamide','centella asiatica','hyaluronic acid'],
 89000, true, false,
 'Sunscreen serum best-seller dengan tone-up effect. Ringan dan tidak lengket.',
 'Usapkan secukupnya (2 ruas jari) pada wajah setelah moisturizer. Reapply tiap 2-3 jam.',
 4.70),

('UV Shield Active Protection Serum SPF 50 PA++++', 'Wardah', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','dullness'],
 ARRAY['niacinamide','vitamin E','aloe vera'],
 49000, true, true,
 'Sunscreen serum ringan dan affordable dari Wardah. Cocok di bawah makeup.',
 'Usapkan 2 ruas jari pada wajah sebagai step terakhir pagi. Reapply tiap 2-3 jam.',
 4.50),

('UV White Aqua Rich Sunscreen SPF 50', 'Wardah', 'sunscreen',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','dryness'],
 ARRAY['hyaluronic acid','vitamin E','niacinamide'],
 55000, true, true,
 'Sunscreen aqua ringan dari Wardah yang tidak bikin lengket di cuaca panas.',
 'Usapkan secukupnya pada wajah 15 menit sebelum keluar rumah. Reapply setiap 2-3 jam.',
 4.50),

('Sunscreen SPF 50 PA++++', 'Glad2Glow', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','dullness'],
 ARRAY['niacinamide','centella asiatica','hyaluronic acid'],
 55000, true, false,
 'Sunscreen ringan yang affordable. No white cast dan cocok di bawah makeup.',
 'Usapkan 2 ruas jari pada wajah sebagai step terakhir pagi. Reapply tiap 2-3 jam.',
 4.50),

('Sunscreen SPF 50 PA++++', 'The Originote', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','oiliness'],
 ARRAY['niacinamide','centella asiatica'],
 35000, true, false,
 'Sunscreen super affordable dengan SPF 50. Cocok buat yang budget-friendly.',
 'Usapkan 2 ruas jari pada wajah setiap pagi. Reapply setiap 2-3 jam.',
 4.30),

('Cica Beat The Sun SPF 50 PA++++', 'NPURE', 'sunscreen',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','redness'],
 ARRAY['centella asiatica','zinc oxide','titanium dioxide'],
 89000, true, false,
 'Sunscreen hybrid (physical + chemical) dengan cica. Aman untuk kulit sensitif.',
 'Usapkan 2 ruas jari pada wajah sebagai step terakhir pagi. Reapply tiap 2-3 jam.',
 4.70),

('Your Skin Bae Sunscreen SPF 50 PA++++', 'Avoskin', 'sunscreen',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','oiliness'],
 ARRAY['niacinamide','centella asiatica','hyaluronic acid'],
 99000, true, false,
 'Sunscreen premium lokal yang ringan dan tidak bikin white cast.',
 'Usapkan secukupnya pada wajah setelah moisturizer. Reapply tiap 2-3 jam.',
 4.60),

('Sun Protection SPF 45', 'Emina', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness'],
 ARRAY['niacinamide','aloe vera','vitamin E'],
 29000, true, true,
 'Sunscreen paling affordable untuk pelajar dan pemula skincare.',
 'Usapkan pada wajah 15 menit sebelum aktivitas outdoor. Reapply tiap 2-3 jam.',
 4.30),

('Triple Protection Sunscreen Moisturizer SPF 30', 'Kahf', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','dullness'],
 ARRAY['niacinamide','hyaluronic acid','vitamin E'],
 45000, true, true,
 'Sunscreen pria yang sekaligus moisturizer. Praktis 2-in-1.',
 'Usapkan secukupnya pada wajah pagi hari sebagai step terakhir. Reapply tiap 3 jam.',
 4.50),

('AquaFusion Moisturizer Sunscreen SPF 50', 'Y.O.U', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','dullness'],
 ARRAY['niacinamide','hyaluronic acid','centella asiatica'],
 65000, true, false,
 'Sunscreen yang juga berfungsi sebagai moisturizer ringan. No white cast.',
 'Usapkan 2 ruas jari pada wajah sebagai step terakhir pagi. Reapply tiap 2-3 jam.',
 4.50),

('Hydrasoothe Sunscreen Gel SPF 45 PA++++', 'Azarine', 'sunscreen',
 ARRAY['oily','combination','sensitive','normal'],
 ARRAY['sensitivity','oiliness'],
 ARRAY['hyaluronic acid','propolis','aloe vera'],
 39000, true, false,
 'Sunscreen gel paling viral di Indonesia. Ringan, tidak lengket, super affordable.',
 'Usapkan 2 ruas jari pada wajah setiap pagi. Reapply tiap 2-3 jam di outdoor.',
 4.80),

('Aloe Soothing Sun Cream SPF 50+ PA+++', 'COSRX', 'sunscreen',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','dryness'],
 ARRAY['aloe vera','vitamin E'],
 149000, true, false,
 'Sunscreen dengan aloe vera yang menenangkan. Cocok untuk kulit sensitif pasca treatment.',
 'Usapkan secukupnya pada wajah setelah moisturizer. Reapply tiap 2-3 jam.',
 4.70),

('Sheer Mineral Sunscreen SPF 50', 'Cetaphil', 'sunscreen',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity'],
 ARRAY['zinc oxide','titanium dioxide','glycerin'],
 185000, true, false,
 'Mineral sunscreen yang gentle untuk kulit sangat sensitif. Physical UV filter.',
 'Usapkan secukupnya pada wajah 15 menit sebelum beraktivitas. Reapply tiap 2 jam.',
 4.60),

('Skin Naturals Bright Complete Super UV Matte SPF 50+', 'Garnier', 'sunscreen',
 ARRAY['oily','combination'],
 ARRAY['oiliness','dullness'],
 ARRAY['vitamin C','niacinamide'],
 49000, true, false,
 'Sunscreen matte finish cocok untuk kulit berminyak. Bisa jadi base makeup.',
 'Usapkan 2 ruas jari pada wajah sebagai step terakhir pagi. Reapply tiap 2-3 jam.',
 4.50),

('Skin Naturals Super UV Spot-Proof SPF 50+ PA+++', 'Garnier', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['dark_spots','oiliness'],
 ARRAY['niacinamide','vitamin C','vitamin E'],
 59000, true, false,
 'Sunscreen anti-spot yang cerahkan sekaligus protect dari UV damage.',
 'Usapkan 2 ruas jari pada wajah setiap pagi. Reapply tiap 2-3 jam.',
 4.50),

('Perfect UV Gel SPF 50 PA++++', 'Hada Labo', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness','dullness'],
 ARRAY['hyaluronic acid','collagen','vitamin C'],
 85000, true, false,
 'Sunscreen gel ringan dari Hada Labo. Cepat meresap dan tidak white cast.',
 'Usapkan secukupnya pada wajah setelah skincare pagi. Reapply tiap 2-3 jam.',
 4.60),

('Bright Beauty Sun Protect SPF 50 PA++', 'Pond''s', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['niacinamide','UVA/UVB filter'],
 35000, true, false,
 'Sunscreen affordable dengan tone-up effect untuk kulit cerah bercahaya.',
 'Usapkan pada wajah setiap pagi. Reapply tiap 2-3 jam saat outdoor.',
 4.40),

('Brightly Ever After Sunscreen SPF 50 PA++++', 'Scarlett', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['glutathione','niacinamide','hyaluronic acid'],
 55000, true, false,
 'Sunscreen brightening dengan glutathione. Protect sekaligus cerahkan.',
 'Usapkan 2 ruas jari pada wajah setiap pagi. Reapply tiap 2-3 jam.',
 4.30),

('Light Daily Moisturizer SPF 35 PA+++', 'CeraVe', 'sunscreen',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity'],
 ARRAY['ceramide','niacinamide','hyaluronic acid'],
 215000, true, false,
 'Moisturizer + sunscreen dengan ceramide. Gentle dan cocok untuk kulit sensitif.',
 'Usapkan secukupnya pada wajah pagi hari sebagai moisturizer + sun protection.',
 4.70),

('5X Ceramide Serum Sunscreen Stick SPF 50', 'Skintific', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness'],
 ARRAY['ceramide','niacinamide'],
 99000, true, false,
 'Sunscreen stick untuk reapply praktis di atas makeup. No mess, tinggal oles.',
 'Usapkan langsung pada wajah untuk reapply. Praktis dibawa ke mana-mana.',
 4.70),

('Holyshield! Sunscreen Shake Shake Body SPF 50', 'Somethinc', 'sunscreen',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness'],
 ARRAY['niacinamide','centella asiatica'],
 79000, true, false,
 'Sunscreen badan ringan water-like texture. Praktis untuk seluruh tubuh.',
 'Kocok sebelum digunakan. Usapkan pada badan yang terpapar sinar matahari.',
 4.50),

('Cicarelief Sunscreen SPF 50+ PA++++', 'Azarine', 'sunscreen',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','redness'],
 ARRAY['centella asiatica','madecassoside','panthenol'],
 45000, true, false,
 'Sunscreen cica untuk kulit sensitif pasca treatment. Menenangkan dan melindungi.',
 'Usapkan 2 ruas jari pada wajah setiap pagi. Reapply tiap 2-3 jam.',
 4.60),

('Vitamin C Daily Glow Sunscreen SPF 50', 'COSRX', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','dark_spots'],
 ARRAY['vitamin C','vitamin E','niacinamide'],
 175000, true, false,
 'Sunscreen dengan vitamin C untuk proteksi UV sekaligus brightening daily.',
 'Usapkan secukupnya pada wajah setelah moisturizer. Reapply tiap 2-3 jam.',
 4.70),

('Sun Active Protect SPF 50 PA++++', 'Kahf', 'sunscreen',
 ARRAY['oily','combination','normal'],
 ARRAY['oiliness'],
 ARRAY['niacinamide','vitamin E','zinc oxide'],
 49000, true, true,
 'Sunscreen pria yang ringan dan tidak lengket. Tahan keringat.',
 'Usapkan 2 ruas jari pada wajah setiap pagi. Reapply setelah keringatan.',
 4.50),

-- ============================================================
-- EXFOLIATORS (~8 products)
-- ============================================================

('AHA BHA PHA Peeling Solution', 'Somethinc', 'exfoliator',
 ARRAY['oily','combination','normal'],
 ARRAY['acne','dullness','blackheads','large_pores'],
 ARRAY['AHA','BHA','PHA','niacinamide'],
 99000, true, false,
 'Chemical peeling solution dengan triple acid. Eksfoliasi intens 1-2x seminggu.',
 'Gunakan 1-2x seminggu malam hari. Usapkan tipis, diamkan 10 menit, bilas. WAJIB sunscreen besoknya.',
 4.60),

('AHA 7 Whitehead Power Liquid', 'COSRX', 'exfoliator',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','blackheads','large_pores'],
 ARRAY['AHA','glycolic acid','apple water'],
 165000, true, false,
 'Chemical exfoliator dengan AHA untuk angkat sel kulit mati dan cerahkan.',
 'Gunakan malam hari setelah toner. Tuang pada kapas, usap searah. Mulai 2-3x seminggu.',
 4.70),

('5% Glycolic Acid Exfoliating Toner', 'Glad2Glow', 'exfoliator',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','blackheads','large_pores'],
 ARRAY['glycolic acid','niacinamide','centella asiatica'],
 55000, true, false,
 'Exfoliating toner glycolic acid yang affordable untuk kulit cerah dan halus.',
 'Gunakan malam hari 2-3x seminggu. Tuang pada kapas, usap searah. Wajib sunscreen besoknya.',
 4.40),

('Daily Peeling Pad', 'Skintific', 'exfoliator',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','blackheads','large_pores','oiliness'],
 ARRAY['AHA','BHA','PHA','ceramide'],
 119000, true, false,
 'Peeling pad praktis dengan AHA BHA PHA + ceramide supaya tidak bikin kering.',
 'Gunakan malam hari 2-3x seminggu. Usap pad pada wajah, fokus di T-zone.',
 4.70),

('Gentle Exfoliating Cleanser', 'Cetaphil', 'exfoliator',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness','blackheads'],
 ARRAY['glycerin','micro-granules'],
 115000, true, false,
 'Physical exfoliator gentle dari Cetaphil. Butiran halus untuk angkat sel kulit mati.',
 'Usapkan pada wajah basah, pijat lembut selama 30 detik, bilas bersih. Gunakan 2-3x seminggu.',
 4.50),

('SA Smoothing Cleanser', 'CeraVe', 'exfoliator',
 ARRAY['oily','combination','normal'],
 ARRAY['acne','blackheads','large_pores'],
 ARRAY['salicylic acid','ceramide','niacinamide'],
 179000, true, false,
 'Exfoliating cleanser dengan salicylic acid + ceramide untuk kulit berjerawat.',
 'Usapkan pada wajah basah, pijat lembut, bilas bersih. Bisa digunakan setiap hari.',
 4.70),

('BHA Blackhead Power Cream', 'COSRX', 'exfoliator',
 ARRAY['oily','combination'],
 ARRAY['blackheads','large_pores','oiliness'],
 ARRAY['BHA','betaine salicylate','centella asiatica'],
 135000, true, false,
 'Cream eksfoliator BHA untuk atasi komedo membandel dan besarkan pori.',
 'Gunakan malam hari. Usapkan tipis pada area berkomedo. Mulai 2-3x seminggu.',
 4.60),

('PHA Peeling Gel', 'Somethinc', 'exfoliator',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dullness','dryness'],
 ARRAY['PHA','gluconolactone','hyaluronic acid'],
 79000, true, false,
 'Peeling gel gentle dengan PHA yang cocok untuk kulit sensitif yang ingin eksfoliasi.',
 'Usapkan pada wajah kering, pijat lembut sampai keluar butiran, bilas bersih. 2-3x seminggu.',
 4.50),

-- ============================================================
-- MASKS (~7 products)
-- ============================================================

('5X Ceramide Skin Barrier Repair Sleeping Mask', 'Skintific', 'mask',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity','dullness'],
 ARRAY['ceramide','hyaluronic acid','squalane'],
 119000, true, false,
 'Sleeping mask dengan ceramide untuk repair barrier semalaman. Bangun dengan kulit bouncy.',
 'Gunakan sebagai step terakhir malam hari. Usapkan tipis, tidur, bilas pagi harinya.',
 4.80),

('AHA BHA PHA Clay Mask', 'Somethinc', 'mask',
 ARRAY['oily','combination'],
 ARRAY['oiliness','blackheads','large_pores'],
 ARRAY['AHA','BHA','PHA','kaolin clay'],
 79000, true, false,
 'Clay mask dengan triple acid untuk deep cleanse pori dan kontrol minyak.',
 'Usapkan pada wajah bersih, diamkan 10-15 menit, bilas. Gunakan 1-2x seminggu.',
 4.50),

('Neem Face Mask', 'Himalaya', 'mask',
 ARRAY['oily','combination'],
 ARRAY['acne','oiliness'],
 ARRAY['neem','turmeric','kaolin'],
 35000, true, false,
 'Clay mask dengan neem dan turmeric untuk kulit berjerawat dan berminyak.',
 'Usapkan merata pada wajah, diamkan 10-15 menit, bilas. 2x seminggu.',
 4.30),

('Hydra Intense Sleeping Mask', 'Wardah', 'mask',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dryness','dullness'],
 ARRAY['hyaluronic acid','aloe vera','vitamin E'],
 49000, true, true,
 'Sleeping mask hydrating dari Wardah untuk hidrasi intens semalaman.',
 'Usapkan tipis pada wajah sebagai step terakhir malam hari. Bilas di pagi hari.',
 4.40),

('Ultimate Power Hyaluronic Acid Overnight Mask', 'COSRX', 'mask',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','dullness','fine_lines'],
 ARRAY['hyaluronic acid','vitamin B5','betaine'],
 175000, true, false,
 'Overnight mask dengan hyaluronic acid untuk hidrasi super intens semalaman.',
 'Gunakan sebagai step terakhir malam hari. Usapkan secukupnya, tidur, bilas pagi.',
 4.70),

('Rice Wash Off Mask', 'Skinfood', 'mask',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','dryness'],
 ARRAY['rice extract','rice bran oil'],
 99000, true, false,
 'Wash-off mask dengan rice extract untuk cerahkan dan lembutkan kulit.',
 'Usapkan pada wajah, diamkan 10-15 menit, bilas sambil pijat lembut.',
 4.50),

('Cica Sleeping Mask', 'NPURE', 'mask',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['sensitivity','redness','acne_scars'],
 ARRAY['centella asiatica','madecassoside','allantoin'],
 79000, true, false,
 'Sleeping mask cica untuk calming dan repair kulit sensitif semalaman.',
 'Usapkan tipis sebagai step terakhir malam. Biarkan semalaman, bilas pagi hari.',
 4.60),

-- ============================================================
-- SPOT TREATMENTS (~5 products)
-- ============================================================

('Acne Pimple Master Patch', 'COSRX', 'spot_treatment',
 ARRAY['oily','combination','sensitive','normal'],
 ARRAY['acne'],
 ARRAY['hydrocolloid'],
 55000, true, false,
 'Patch jerawat best-seller. Serap nanah dan lindungi jerawat dari sentuhan/bakteri.',
 'Tempel pada jerawat yang sudah ada head-nya. Ganti setiap 8-12 jam.',
 4.90),

('Clear Fit Master Patch', 'COSRX', 'spot_treatment',
 ARRAY['oily','combination','sensitive','normal'],
 ARRAY['acne'],
 ARRAY['hydrocolloid'],
 65000, true, false,
 'Versi transparan dari pimple patch. Bisa dipakai siang hari tanpa kelihatan.',
 'Tempel pada jerawat yang sudah ada head. Bisa dipakai di bawah makeup.',
 4.80),

('Acne Spot Gel', 'Wardah', 'spot_treatment',
 ARRAY['oily','combination'],
 ARRAY['acne'],
 ARRAY['salicylic acid','sulfur','tea tree'],
 35000, true, true,
 'Spot treatment gel untuk jerawat meradang. Keringkan jerawat dengan cepat.',
 'Oleskan tipis pada jerawat sebelum tidur. Gunakan sebagai spot treatment saja.',
 4.40),

('5X Ceramide Acne Spot Treatment', 'Skintific', 'spot_treatment',
 ARRAY['oily','combination','sensitive'],
 ARRAY['acne'],
 ARRAY['salicylic acid','ceramide','tea tree'],
 79000, true, false,
 'Spot treatment jerawat dengan ceramide supaya tidak kering berlebihan.',
 'Oleskan tipis langsung pada jerawat. Bisa digunakan pagi dan malam.',
 4.60),

('Acne Pimple Patch', 'Somethinc', 'spot_treatment',
 ARRAY['oily','combination','sensitive','normal'],
 ARRAY['acne'],
 ARRAY['hydrocolloid','tea tree','salicylic acid'],
 39000, true, false,
 'Pimple patch lokal dengan hydrocolloid + tea tree untuk serap jerawat lebih cepat.',
 'Tempel pada jerawat bersih yang sudah ada head. Ganti setiap 8-12 jam.',
 4.50),

-- ============================================================
-- EYE CREAM (~4 products)
-- ============================================================

('5X Ceramide Eye Cream', 'Skintific', 'eye_cream',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['fine_lines','dark_circles'],
 ARRAY['ceramide','peptide','caffeine','niacinamide'],
 129000, true, false,
 'Eye cream dengan ceramide dan peptide untuk samarkan garis halus dan mata panda.',
 'Ambil sedikit dengan jari manis, tepuk lembut di area bawah mata. Gunakan pagi dan malam.',
 4.60),

('AHC Ten Revolution Real Eye Cream', 'AHC', 'eye_cream',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['fine_lines','dark_circles'],
 ARRAY['collagen','peptide','hyaluronic acid'],
 159000, true, false,
 'Eye cream Korea populer di Indonesia. Bisa juga dipakai untuk seluruh wajah.',
 'Tepuk lembut pada area mata dengan jari manis. Bisa juga dipakai di area smile lines.',
 4.60),

('Retinol Eye Cream', 'Somethinc', 'eye_cream',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['fine_lines','dark_circles'],
 ARRAY['retinol','caffeine','peptide','squalane'],
 109000, true, false,
 'Eye cream dengan retinol untuk anti-aging area mata. Samarkan wrinkles dan dark circles.',
 'Gunakan malam hari. Tepuk lembut pada area mata. Mulai 2-3x seminggu.',
 4.50),

('Renew You Anti-Aging Eye Cream', 'Wardah', 'eye_cream',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['fine_lines','dark_circles'],
 ARRAY['retinol','peptide','vitamin E'],
 75000, true, true,
 'Eye cream anti-aging affordable dari Wardah untuk samarkan kerutan di area mata.',
 'Tepuk lembut pada area mata pagi dan malam menggunakan jari manis.',
 4.40),

-- ============================================================
-- LIP CARE (~4 products)
-- ============================================================

('Lip Sleeping Mask', 'Laneige', 'lip_care',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness'],
 ARRAY['vitamin C','berry extract','hyaluronic acid'],
 165000, true, false,
 'Sleeping mask bibir best-seller. Bikin bibir super lembut dan plump di pagi hari.',
 'Oleskan tipis pada bibir sebelum tidur. Bisa juga dipakai siang sebagai lip balm.',
 4.90),

('Lip Moisturizer', 'Wardah', 'lip_care',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness'],
 ARRAY['vitamin E','olive oil','jojoba oil'],
 25000, true, true,
 'Lip balm affordable dari Wardah yang bikin bibir lembap sepanjang hari.',
 'Oleskan pada bibir kapan saja terasa kering. Bisa dipakai sebelum lipstik.',
 4.40),

('Lip Serum Nourishing', 'Emina', 'lip_care',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','dullness'],
 ARRAY['vitamin E','jojoba oil','shea butter'],
 29000, true, true,
 'Lip serum ringan untuk merawat dan melembapkan bibir kering.',
 'Oleskan pada bibir 2-3x sehari atau sebelum tidur.',
 4.30),

('Lip Sleeping Mask Berry', 'Somethinc', 'lip_care',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness'],
 ARRAY['shea butter','vitamin E','berry extract'],
 65000, true, false,
 'Lip sleeping mask lokal alternatif yang sama efektifnya. Bibir super halus di pagi hari.',
 'Oleskan tipis pada bibir sebelum tidur. Bilas lembut di pagi hari.',
 4.50),

-- ============================================================
-- BODY LOTION (~5 products)
-- ============================================================

('Brightly Ever After Body Lotion', 'Scarlett', 'body_lotion',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','dryness'],
 ARRAY['glutathione','vitamin E','collagen'],
 39000, true, false,
 'Body lotion brightening paling viral di Indonesia. Wangi tahan lama dan kulit cerah.',
 'Oleskan pada seluruh badan setelah mandi. Gunakan 2x sehari.',
 4.50),

('Goat Milk Body Lotion', 'Scarlett', 'body_lotion',
 ARRAY['dry','sensitive','normal'],
 ARRAY['dryness','sensitivity'],
 ARRAY['goat milk','vitamin E','shea butter'],
 39000, true, false,
 'Body lotion dengan goat milk untuk kulit kering dan sensitif. Extra moisturizing.',
 'Oleskan merata setelah mandi pada seluruh badan.',
 4.40),

('Body Lotion Healthy & Glow', 'Wardah', 'body_lotion',
 ARRAY['oily','dry','combination','normal'],
 ARRAY['dullness','dryness'],
 ARRAY['niacinamide','vitamin E','olive oil'],
 32000, true, true,
 'Body lotion halal dari Wardah untuk kulit cerah dan sehat.',
 'Oleskan merata pada badan setelah mandi pagi dan malam.',
 4.30),

('Moisturizing Lotion', 'CeraVe', 'body_lotion',
 ARRAY['oily','dry','combination','sensitive','normal'],
 ARRAY['dryness','sensitivity'],
 ARRAY['ceramide','hyaluronic acid','glycerin'],
 225000, true, false,
 'Body lotion premium dengan 3 essential ceramide. Hidrasi tahan 24 jam.',
 'Oleskan secukupnya pada badan setelah mandi. Cocok juga untuk wajah.',
 4.80),

('Green Tea Body Lotion', 'Emina', 'body_lotion',
 ARRAY['oily','combination','normal'],
 ARRAY['dullness'],
 ARRAY['green tea','vitamin E','allantoin'],
 19000, true, true,
 'Body lotion super affordable dengan green tea. Segar dan ringan di kulit.',
 'Oleskan pada badan setelah mandi. Segar untuk cuaca panas.',
 4.20);
